import type { Locale } from "@/lib/types";

const en = {
  title: "A workspace for your hackathon",
  subtitle: "From a first idea to a working handoff. Start with what you know; organize the rest as you go.",
  eyebrow: "ProjectHub / Workspaces",
  local: "Saved on this device",
  localNote: "Work stays in this browser. Export a backup before clearing browser data or switching devices. This local workspace is independent of any shared copies.",
  loading: "Opening your workspaces…",
  create: "New hackathon",
  createTitle: "Start with a name. Build from there.",
  createBody: "No event website or advance planning needed. You can add a deadline and projects later.",
  eventName: "Hackathon name",
  eventPlaceholder: "e.g. Community Build Weekend",
  objective: "What are you here to achieve?",
  optional: "Optional",
  deadline: "Event deadline",
  localTime: "Dates use your device’s time zone.",
  mode: "How are you starting?",
  modes: { planned: "Planned event", rapid: "Rapid build", crisis: "Crisis response" },
  modeNotes: {
    planned: "Plan scope, build a demo and prepare a submission.",
    rapid: "Focus on one useful result and a quick handoff.",
    crisis: "Verify the need, build a useful tool and identify a maintainer.",
  },
  start: "Create workspace",
  cancel: "Cancel",
  save: "Save changes",
  eventSettings: "Event settings",
  switchEvent: "Hackathon",
  export: "Export backup",
  import: "Import workspace",
  importConfirm: "Import as a new workspace",
  importPreview: "Review this backup. Importing creates a separate workspace and keeps your existing work.",
  importError: "This is not a valid ProjectHub v1 backup, or it exceeds 2 MB. Your existing work is unchanged.",
  saveError: "Could not save. Your previous saved work is intact. Check available browser storage and try again.",
  corrupt: "Saved work could not be read. Export the recovery file before changing browser data. Existing data has not been replaced.",
  recovery: "Download recovery file",
  unavailable: "Browser storage is unavailable. Enable site storage to save a workspace on this device.",
  conflict: "This workspace changed in another tab. Reopen the form to use the latest version.",
  saved: "Changes saved on this device.",
  noDeadline: "No deadline set",
  deadlinePassed: "Deadline passed",
  projectCount: "projects",
  projects: "Projects",
  newProject: "Add project",
  projectName: "Project name",
  projectGoal: "What will you deliver?",
  emptyProjects: "Make room for your first idea",
  emptyProjectsBody: "Add a project, define a useful outcome, then give the next task an owner.",
  editProject: "Project details",
  tasks: "Tasks",
  addTask: "Add task",
  editTask: "Edit task",
  taskTitle: "What needs to happen?",
  owner: "Owner",
  unassigned: "Unassigned",
  due: "Due date",
  priority: "Priority",
  priorities: { high: "High", normal: "Normal", low: "Low" },
  status: "Status",
  statuses: { todo: "To do", doing: "In progress", blocked: "Blocked", done: "Done" },
  blocker: "What is blocking this?",
  blockerHint: "Name the dependency or help needed.",
  noTasks: "No tasks here yet.",
  emptyTasks: "Start with the next useful step.",
  emptyTasksBody: "Keep tasks small enough to finish during this hackathon.",
  completed: "completed",
  overdue: "Overdue",
  allTasks: "All tasks",
  search: "Search tasks or owners",
  onlyAttention: "Needs attention",
  attentionHint: "Blocked, overdue or without an owner",
  noMatches: "No tasks match this view.",
  readiness: "Delivery checklist",
  readinessNote: "A starting guide, not the event’s official requirements. Edit it to match your handoff.",
  checklistItem: "Checklist item",
  editChecklist: "Edit delivery checklist",
  removeChecklistNote: "Leave a title empty to remove that item when you save.",
  addItem: "Add item",
  links: "Project links",
  repo: "Repository URL",
  demo: "Demo URL",
  submission: "Submission URL",
  openRepo: "Open repository",
  openDemo: "Open demo",
  openSubmission: "Open submission",
  invalid: "Check the highlighted fields. Use valid http(s) links and keep names within 120 characters.",
  template: "Include a starter checklist",
  starter: "Start from this project",
  starterNote: "This creates your own local plan. It does not change the public project or join its team.",
  boardCta: "Plan your hackathon",
  boardBody: "Turn an idea into tasks, owners and a delivery plan — for Build4Venezuela or your next event.",
  boardLink: "Open workspace",
  templates: {
    planned: ["Agree on the MVP scope", "Test the main user journey", "Prepare a working demo", "Check the event’s submission requirements"],
    rapid: ["Choose one useful outcome", "Test the smallest working version", "Write a short handoff"],
    crisis: ["Verify the need and source with a coordinator", "Test the tool with its intended user", "Document limitations and data handling", "Name a maintainer and hand off"],
  },
};

const es: typeof en = {
  title: "Un espacio para tu hackathon",
  subtitle: "De la primera idea a una entrega útil. Empieza con lo que sabes; organiza lo demás sobre la marcha.",
  eyebrow: "ProjectHub / Espacios de trabajo",
  local: "Guardado en este dispositivo",
  localNote: "El trabajo queda en este navegador. Exporta una copia antes de borrar sus datos o cambiar de dispositivo. Este espacio local es independiente de sus copias compartidas.",
  loading: "Abriendo tus espacios…",
  create: "Nuevo hackathon",
  createTitle: "Empieza con un nombre. Construye desde ahí.",
  createBody: "No necesitas una web del evento ni planificación previa. Puedes añadir una fecha y proyectos después.",
  eventName: "Nombre del hackathon",
  eventPlaceholder: "ej. Fin de semana de construcción comunitaria",
  objective: "¿Qué quieres lograr?",
  optional: "Opcional",
  deadline: "Fecha límite del evento",
  localTime: "Las fechas usan la zona horaria de tu dispositivo.",
  mode: "¿Cómo empiezas?",
  modes: { planned: "Evento planificado", rapid: "Construcción rápida", crisis: "Respuesta a crisis" },
  modeNotes: {
    planned: "Define el alcance, construye una demo y prepara la entrega.",
    rapid: "Enfócate en un resultado útil y un traspaso rápido.",
    crisis: "Verifica la necesidad, crea una herramienta útil e identifica quién la mantendrá.",
  },
  start: "Crear espacio",
  cancel: "Cancelar",
  save: "Guardar cambios",
  eventSettings: "Ajustes del evento",
  switchEvent: "Hackathon",
  export: "Exportar copia",
  import: "Importar espacio",
  importConfirm: "Importar como espacio nuevo",
  importPreview: "Revisa esta copia. Al importar se crea un espacio independiente y se conserva tu trabajo actual.",
  importError: "No es una copia válida de ProjectHub v1 o supera los 2 MB. Tu trabajo actual sigue intacto.",
  saveError: "No se pudo guardar. El trabajo guardado antes sigue intacto. Comprueba el espacio del navegador y vuelve a intentarlo.",
  corrupt: "No se pudo leer el trabajo guardado. Descarga el archivo de recuperación antes de cambiar los datos del navegador. No se ha reemplazado nada.",
  recovery: "Descargar archivo de recuperación",
  unavailable: "El almacenamiento del navegador no está disponible. Habilítalo para guardar un espacio en este dispositivo.",
  conflict: "Este espacio cambió en otra pestaña. Abre el formulario de nuevo para usar la última versión.",
  saved: "Cambios guardados en este dispositivo.",
  noDeadline: "Sin fecha límite",
  deadlinePassed: "Fecha límite vencida",
  projectCount: "proyectos",
  projects: "Proyectos",
  newProject: "Añadir proyecto",
  projectName: "Nombre del proyecto",
  projectGoal: "¿Qué vas a entregar?",
  emptyProjects: "Dale espacio a tu primera idea",
  emptyProjectsBody: "Añade un proyecto, define un resultado útil y asigna la próxima tarea.",
  editProject: "Detalles del proyecto",
  tasks: "Tareas",
  addTask: "Añadir tarea",
  editTask: "Editar tarea",
  taskTitle: "¿Qué hay que hacer?",
  owner: "Responsable",
  unassigned: "Sin asignar",
  due: "Fecha de entrega",
  priority: "Prioridad",
  priorities: { high: "Alta", normal: "Normal", low: "Baja" },
  status: "Estado",
  statuses: { todo: "Por hacer", doing: "En curso", blocked: "Bloqueado", done: "Hecho" },
  blocker: "¿Qué lo bloquea?",
  blockerHint: "Indica la dependencia o la ayuda necesaria.",
  noTasks: "Aún no hay tareas aquí.",
  emptyTasks: "Empieza con el próximo paso útil.",
  emptyTasksBody: "Crea tareas lo bastante pequeñas para terminarlas durante este hackathon.",
  completed: "completadas",
  overdue: "Vencida",
  allTasks: "Todas las tareas",
  search: "Buscar tareas o responsables",
  onlyAttention: "Necesitan atención",
  attentionHint: "Bloqueadas, vencidas o sin responsable",
  noMatches: "Ninguna tarea coincide con esta vista.",
  readiness: "Lista de entrega",
  readinessNote: "Una guía inicial, no los requisitos oficiales del evento. Adáptala a tu entrega.",
  checklistItem: "Punto de la lista",
  editChecklist: "Editar lista de entrega",
  removeChecklistNote: "Deja un título vacío para quitar ese punto al guardar.",
  addItem: "Añadir punto",
  links: "Enlaces del proyecto",
  repo: "URL del repositorio",
  demo: "URL de la demo",
  submission: "URL de la entrega",
  openRepo: "Abrir repositorio",
  openDemo: "Abrir demo",
  openSubmission: "Abrir entrega",
  invalid: "Revisa los campos indicados. Usa enlaces http(s) válidos y nombres de hasta 120 caracteres.",
  template: "Incluir una lista de entrega inicial",
  starter: "Empezar desde este proyecto",
  starterNote: "Esto crea tu propio plan local. No cambia el proyecto público ni te une a su equipo.",
  boardCta: "Organiza tu hackathon",
  boardBody: "Convierte una idea en tareas, responsables y una entrega — para Build4Venezuela o tu próximo evento.",
  boardLink: "Abrir espacio de trabajo",
  templates: {
    planned: ["Acordar el alcance del MVP", "Probar el recorrido principal", "Preparar una demo funcional", "Revisar los requisitos de entrega del evento"],
    rapid: ["Elegir un resultado útil", "Probar la versión mínima funcional", "Escribir un traspaso breve"],
    crisis: ["Verificar la necesidad y la fuente con un coordinador", "Probar la herramienta con su usuario", "Documentar límites y manejo de datos", "Identificar responsable y realizar el traspaso"],
  },
};

export type WorkspaceCopy = typeof en;
export const workspaceCopy: Record<Locale, WorkspaceCopy> = { en, es };
