import type { Locale } from "@/lib/types";

const en = {
  eyebrow: "ProjectHub / Any hackathon",
  title: "An idea. A plan. A place to start.",
  description: "Start a project for a weekend build, a last-minute challenge or a community response. Keep the work and its context together.",
  steps: ["Define one useful outcome", "Work through a small, editable plan", "Hand over the context and next steps"],
  formTitle: "What are you building?",
  formNote: "One step creates your workspace, first project, three starter tasks and a delivery checklist.",
  goalPlaceholder: "A working demo that helps…",
  contextPlaceholder: "Who is this for? What do we know? What is out of scope? Add constraints, decisions, sources or instructions for the next person.",
  options: "Event, timing and task owner",
  eventPlaceholder: "Optional — use any event name",
  duration: "Time available",
  noDeadline: "No deadline yet",
  hours: "hours from now",
  ownerNote: "A name or team label for the starter tasks; no invitation is sent.",
  submit: "Create my project plan",
  creating: "Saving your plan…",
  continue: "Continue existing work",
  savedWork: "Your existing work stays in My workspace.",
  selectionMissing: "This saved project or event is not in this browser. Open your existing work here, or import a project backup to continue on this device.",
  localTitle: "Ready without an account",
  localBody: "Your plan is saved in this browser. Export a backup before changing devices or clearing browser data.",
  handoffTitle: "Easy to hand over",
  handoffBody: "Copy a readable brief for your team or download a project backup they can import. Each copy is a snapshot; edits do not sync.",
  limitsTitle: "Your event, your rules",
  limitsBody: "The starter plan is editable. Check your event’s actual rules and deadlines. Crisis mode is a planning aid, not an emergency service.",
  homeTitle: "Starting another hackathon?",
  homeBody: "Create a project plan for any event, with tasks, context and a handoff ready to share.",
  homeAction: "Start a project",
  handoff: "Share context and handoff",
  handoffNote: "Review before sharing. This snapshot includes only this project and the event context. Anyone you send it to can read it; copies do not sync.",
  preview: "Project handoff preview",
  copy: "Copy handoff",
  copied: "Handoff copied. Paste it into your team’s chat or document.",
  copyFailed: "Clipboard access is unavailable. Select the text below or download the file.",
  markdown: "Download Markdown",
  backup: "Download project backup",
};
const es: typeof en = {
  eyebrow: "ProjectHub / Cualquier hackathon",
  title: "Una idea. Un plan. Un punto de partida.",
  description: "Empieza un proyecto para un fin de semana, un reto de última hora o una respuesta comunitaria. Mantén el trabajo y su contexto juntos.",
  steps: ["Define un resultado útil", "Avanza con un plan pequeño y editable", "Entrega el contexto y los próximos pasos"],
  formTitle: "¿Qué vas a construir?",
  formNote: "Un solo paso crea tu espacio, el primer proyecto, tres tareas iniciales y una lista de entrega.",
  goalPlaceholder: "Una demo funcional que ayude a…",
  contextPlaceholder: "¿Para quién es? ¿Qué sabemos? ¿Qué queda fuera? Añade límites, decisiones, fuentes o instrucciones para la siguiente persona.",
  options: "Evento, tiempo y responsable",
  eventPlaceholder: "Opcional — usa el nombre de cualquier evento",
  duration: "Tiempo disponible",
  noDeadline: "Sin fecha límite todavía",
  hours: "horas desde ahora",
  ownerNote: "Un nombre o equipo para las tareas iniciales; no se envía ninguna invitación.",
  submit: "Crear mi plan de proyecto",
  creating: "Guardando tu plan…",
  continue: "Continuar mi trabajo",
  savedWork: "Tu trabajo anterior sigue en Mi espacio.",
  selectionMissing: "Este proyecto o evento no está guardado en este navegador. Abre tu trabajo anterior aquí o importa una copia del proyecto para continuar en este dispositivo.",
  localTitle: "Listo sin una cuenta",
  localBody: "El plan se guarda en este navegador. Exporta una copia antes de cambiar de dispositivo o borrar sus datos.",
  handoffTitle: "Fácil de entregar",
  handoffBody: "Copia un resumen para tu equipo o descarga una copia del proyecto que puedan importar. Cada copia es una instantánea; los cambios no se sincronizan.",
  limitsTitle: "Tu evento, tus reglas",
  limitsBody: "El plan inicial es editable. Revisa las reglas y fechas reales del evento. El modo crisis ayuda a planificar; no es un servicio de emergencias.",
  homeTitle: "¿Empiezas otro hackathon?",
  homeBody: "Crea un plan para cualquier evento, con tareas, contexto y un resumen listo para compartir.",
  homeAction: "Empezar un proyecto",
  handoff: "Compartir contexto y entrega",
  handoffNote: "Revisa antes de compartir. Esta instantánea incluye solo este proyecto y el contexto del evento. Quien la reciba podrá leerla; las copias no se sincronizan.",
  preview: "Vista previa del resumen del proyecto",
  copy: "Copiar resumen",
  copied: "Resumen copiado. Pégalo en el chat o documento de tu equipo.",
  copyFailed: "No se pudo usar el portapapeles. Selecciona el texto de abajo o descarga el archivo.",
  markdown: "Descargar Markdown",
  backup: "Descargar copia del proyecto",
};
export const quickCopy: Record<Locale, typeof en> = { en, es };
