const en = {
  title: "Shared workspaces", share: "Share with a team", local: "My local workspaces",
  body: "Create a shared copy for your team. Your local workspace remains on this device.",
  consent: "Project details, tasks and owner labels will be stored online. Only invited participants can access this workspace. Avoid sensitive personal or incident data.",
  guest: "Access is remembered in this browser. Save your owner recovery link to return from another device or after clearing browser data.",
  label: "Your name in this workspace", create: "Create shared copy", creating: "Creating…",
  recovery: "Owner recovery link", recoveryNote: "Keep this link private: it grants owner access. It is shown only when created. Anyone with it can manage the workspace.",
  downloadRecovery: "Download recovery link", open: "Open shared workspace", back: "Back to local workspaces",
  titleJoin: "Join a shared workspace", join: "Join workspace", joinNote: "Your invitation grants the role selected by its owner. Invitations can be used once and expire after 7 days.",
  saved: "Saved online", shared: "Shared with your team", readOnly: "View-only access", refreshing: "Checking for updates…",
  note: "Saved online. Updates appear automatically while this page is open. Export a backup for offline use. Task owners are labels, not verified identities.",
  unavailable: "Shared workspaces are temporarily unavailable. Your local work is safe. Try again shortly.",
  access: "This browser does not have access. Open a valid invitation or your owner recovery link.",
  invalid: "Check the form and try again.", limit: "The workspace limit was reached. Please wait and try again, or continue locally.",
  conflict: "Someone saved a newer version. Your form is still open; copy any unsaved text, then cancel and reopen it to use the latest version.",
  offline: "Connection lost. Changes cannot be saved until you reconnect. Your open form is still available.",
  retry: "Try again", team: "Team access", invite: "Create invitation", editor: "Can edit", viewer: "Can view", owner: "Owner",
  inviteRole: "Invitation permission", copy: "Copy link", copied: "Link copied", copyFailed: "Could not copy. Download the link instead.", download: "Download link",
  inviteNote: "Single-use link, valid for 7 days. Send it only to the intended participant.",
  pending: "Unused invitations", revoke: "Revoke invitation", remove: "Remove access", cancel: "Cancel",
  confirmRemove: "Remove this participant’s access?", rotate: "Replace recovery link", confirmRotate: "Replace the recovery link? The previous link will stop granting access. Existing participants keep their access.",
  activity: "Recent activity", actions: { created: "Workspace created", joined: "Participant joined", saved: "Work updated", invite: "Invitation created", revoke_invite: "Invitation revoked", remove_member: "Access removed", recovery: "Recovery link replaced" },
  revision: "Version", teamHint: "Owners manage access. Editors change work. Viewers can read and export.",
};
const es: typeof en = {
  title: "Espacios compartidos", share: "Compartir con un equipo", local: "Mis espacios locales",
  body: "Crea una copia compartida para tu equipo. El espacio local permanece en este dispositivo.",
  consent: "Los proyectos, tareas y nombres de responsables se guardarán en línea. Solo los participantes invitados tendrán acceso. Evita datos personales sensibles o reportes de incidentes.",
  guest: "El acceso se recuerda en este navegador. Guarda el enlace de recuperación para volver desde otro dispositivo o después de borrar sus datos.",
  label: "Tu nombre en este espacio", create: "Crear copia compartida", creating: "Creando…",
  recovery: "Enlace de recuperación del propietario", recoveryNote: "Guarda este enlace en privado: concede acceso de propietario. Solo se muestra al crearlo. Quien lo tenga podrá administrar el espacio.",
  downloadRecovery: "Descargar enlace de recuperación", open: "Abrir espacio compartido", back: "Volver a espacios locales",
  titleJoin: "Unirse a un espacio compartido", join: "Unirme al espacio", joinNote: "La invitación concede el permiso elegido por su propietario. Se usa una sola vez y vence en 7 días.",
  saved: "Guardado en línea", shared: "Compartido con tu equipo", readOnly: "Acceso de lectura", refreshing: "Buscando actualizaciones…",
  note: "Guardado en línea. Las actualizaciones aparecen mientras esta página esté abierta. Exporta una copia para usarla sin conexión. Los responsables son etiquetas, no identidades verificadas.",
  unavailable: "Los espacios compartidos no están disponibles temporalmente. Tu trabajo local está a salvo. Inténtalo de nuevo en un momento.",
  access: "Este navegador no tiene acceso. Abre una invitación válida o tu enlace de recuperación.",
  invalid: "Revisa el formulario e inténtalo de nuevo.", limit: "Se alcanzó el límite del espacio. Espera e inténtalo de nuevo o continúa de forma local.",
  conflict: "Alguien guardó una versión más reciente. El formulario sigue abierto; copia el texto sin guardar, cancela y vuelve a abrirlo para usar la versión actual.",
  offline: "Se perdió la conexión. No se puede guardar hasta recuperarla. El formulario abierto sigue disponible.",
  retry: "Reintentar", team: "Acceso del equipo", invite: "Crear invitación", editor: "Puede editar", viewer: "Puede ver", owner: "Propietario",
  inviteRole: "Permiso de la invitación", copy: "Copiar enlace", copied: "Enlace copiado", copyFailed: "No se pudo copiar. Descarga el enlace.", download: "Descargar enlace",
  inviteNote: "Enlace de un solo uso, válido por 7 días. Envíalo solo al participante previsto.",
  pending: "Invitaciones sin usar", revoke: "Revocar invitación", remove: "Quitar acceso", cancel: "Cancelar",
  confirmRemove: "¿Quitar el acceso de este participante?", rotate: "Reemplazar enlace de recuperación", confirmRotate: "¿Reemplazar el enlace de recuperación? El anterior dejará de conceder acceso. Los participantes actuales conservarán el suyo.",
  activity: "Actividad reciente", actions: { created: "Espacio creado", joined: "Participante incorporado", saved: "Trabajo actualizado", invite: "Invitación creada", revoke_invite: "Invitación revocada", remove_member: "Acceso retirado", recovery: "Enlace de recuperación reemplazado" },
  revision: "Versión", teamHint: "Los propietarios administran el acceso. Los editores modifican el trabajo. Los lectores pueden consultar y exportar.",
};
export const sharedCopy = { en, es };
export type SharedCopy = typeof en;
